### ISSUE TITLE
Tracker: Unfork cometbft

### ISSUE THREAD

**Issue by hoank101** [orbitorg/core#2]
Compare change -> https://github.com/cometbft/cometbft/compare/v0.37.4...classic-terra:v0.37.4-terra1

## Main changes
- [x] Integrate mempool to `terrad`
- [x] Directly order oracle tx first instead of in the CometBFT's side

## Unit testing
- [x] [Mempool fifo test](https://github.com/orbitorg/core/pull/16/files#diff-5143c5dfcdb6821bc2b114cc5d0e6330fe21a36acd12902fd4f10d8bfd1fe78d)
- [x] [BlockHeightMiddleware test](https://github.com/orbitorg/core/pull/16/files#diff-76fa24638a146388f705a7d9f7dc80e2b52df5b18164eca4efbd533402151776)
- [x] [Override config cache size test](https://github.com/orbitorg/core/pull/16/files#diff-f4ceabccfc54292765cf2b3bc100b0c57537b0f13b921b672ff4a41753d2d15e)
- [x] [Staking logic has test already](https://github.com/orbitorg/core/blob/1039e511916c4aca9b3cce8e86386f66777c4758/custom/staking/module_test.go)
## E2E testings
- [x] [Bash script for testing tx submissions](https://github.com/orbitorg/core/pull/16/files#diff-708587a14c3702fafe1f0e7ebc0da8945ce9a08b30bc3c5a615360405f43db0e)
- [x] [Interchaintest tests for testing tx ordering](https://github.com/orbitorg/core/pull/16/files#diff-57f8911cd5e060838c816336cb1709229899087f6edebf269196fe4f77b77e6e)
